# Generated by Django 5.0.4 on 2024-04-29 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_clients'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clients',
            name='username',
        ),
        migrations.AddField(
            model_name='clients',
            name='fullname',
            field=models.CharField(default='Anonymous', max_length=20),
        ),
        migrations.AlterField(
            model_name='clients',
            name='email',
            field=models.EmailField(max_length=20),
        ),
    ]
