# Generated by Django 5.0.4 on 2024-04-29 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_clients_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='fullname',
            field=models.CharField(max_length=20),
        ),
    ]
