# Generated by Django 5.0.4 on 2024-04-27 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='transmisson',
            new_name='transmission',
        ),
        migrations.DeleteModel(
            name='LikedListing',
        ),
    ]
