# Generated by Django 5.0.4 on 2024-04-29 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='vin',
            new_name='Fuel',
        ),
    ]
