# Generated by Django 5.0.4 on 2024-04-29 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_rentlist_renter'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentlist',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='rentlist',
            name='phone',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
